apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-cart
  labels:
    app: postgres-cart
spec:
  serviceName: postgres-cart
  replicas: 1
  selector:
    matchLabels:
      app: postgres-cart
  template:
    metadata:
      labels:
        app: postgres-cart
    spec:
      securityContext:
        fsGroup: 999
        runAsGroup: 999
        runAsUser: 999
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "cart"
        - name: POSTGRES_USER
          value: "cartuser"
        - name: POSTGRES_PASSWORD
          value: "cartpass"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        resources:
          requests:
            cpu: 70m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "cartuser", "-d", "cart"]
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "cartuser", "-d", "cart"]
          initialDelaySeconds: 15
          periodSeconds: 10
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-cart
  labels:
    app: postgres-cart
spec:
  type: ClusterIP
  selector:
    app: postgres-cart
  ports:
  - name: tcp-postgres
    port: 5432
    targetPort: 5432
